#[derive(Clone, Copy, PartialEq)]
pub enum InstructionType {
    ABC,
    ABx,
    AsBx,
}

pub static INSTRUCTION_TYPE_MAP: [InstructionType; 38] = [
    InstructionType::ABC,
    InstructionType::ABx,
    InstructionType::ABC,
    InstructionType::ABC,
    InstructionType::ABC,
    InstructionType::ABx,
    InstructionType::ABC,
    InstructionType::ABx,
    InstructionType::ABC,
    InstructionType::ABC,
    InstructionType::ABC,
    InstructionType::ABC,
    InstructionType::ABC,
    InstructionType::ABC,
    InstructionType::ABC,
    InstructionType::ABC,
    InstructionType::ABC,
    InstructionType::ABC,
    InstructionType::ABC,
    InstructionType::ABC,
    InstructionType::ABC,
    InstructionType::ABC,
    InstructionType::AsBx,
    InstructionType::ABC,
    InstructionType::ABC,
    InstructionType::ABC,
    InstructionType::ABC,
    InstructionType::ABC,
    InstructionType::ABC,
    InstructionType::ABC,
    InstructionType::ABC,
    InstructionType::AsBx,
    InstructionType::AsBx,
    InstructionType::ABC,
    InstructionType::ABC,
    InstructionType::ABC,
    InstructionType::ABx,
    InstructionType::ABC,
];
