use lua_deserializer::enums::opcode_type::OpcodeType;

#[derive(Clone, Copy, Debug, PartialEq)]
pub enum VMOpcodeType {
    OpMove,
    OpLoadConst,
    OpLoadBool,
    OpLoadNil,
    OpGetUpval,
    OpGetGlobal,
    OpGetTable,
    OpSetGlobal,
    OpSetUpval,
    OpSetTable,
    OpNewTable,
    OpSelf,
    OpAdd,
    OpSub,
    OpMul,
    OpDiv,
    OpMod,
    OpPow,
    OpUnm,
    OpNot,
    OpLen,
    OpConcat,
    OpJmp,
    OpEq,
    OpLt,
    OpLe,
    OpTest,
    OpTestSet,
    OpCall,
    OpTailCall,
    OpReturn,
    OpForLoop,
    OpForPrep,
    OpTForLoop,
    OpSetList,
    OpClose,
    OpClosure,
    OpVarArg,
}

impl From<OpcodeType> for VMOpcodeType {
    fn from(op: OpcodeType) -> Self {
        match op {
            OpcodeType::OpMove => Self::OpMove,
            OpcodeType::OpLoadConst => Self::OpLoadConst,
            OpcodeType::OpLoadBool => Self::OpLoadBool,
            OpcodeType::OpLoadNil => Self::OpLoadNil,
            OpcodeType::OpGetUpval => Self::OpGetUpval,
            OpcodeType::OpGetGlobal => Self::OpGetGlobal,
            OpcodeType::OpGetTable => Self::OpGetTable,
            OpcodeType::OpSetGlobal => Self::OpSetGlobal,
            OpcodeType::OpSetUpval => Self::OpSetUpval,
            OpcodeType::OpSetTable => Self::OpSetTable,
            OpcodeType::OpNewTable => Self::OpNewTable,
            OpcodeType::OpSelf => Self::OpSelf,
            OpcodeType::OpAdd => Self::OpAdd,
            OpcodeType::OpSub => Self::OpSub,
            OpcodeType::OpMul => Self::OpMul,
            OpcodeType::OpDiv => Self::OpDiv,
            OpcodeType::OpMod => Self::OpMod,
            OpcodeType::OpPow => Self::OpPow,
            OpcodeType::OpUnm => Self::OpUnm,
            OpcodeType::OpNot => Self::OpNot,
            OpcodeType::OpLen => Self::OpLen,
            OpcodeType::OpConcat => Self::OpConcat,
            OpcodeType::OpJmp => Self::OpJmp,
            OpcodeType::OpEq => Self::OpEq,
            OpcodeType::OpLt => Self::OpLt,
            OpcodeType::OpLe => Self::OpLe,
            OpcodeType::OpTest => Self::OpTest,
            OpcodeType::OpTestSet => Self::OpTestSet,
            OpcodeType::OpCall => Self::OpCall,
            OpcodeType::OpTailCall => Self::OpTailCall,
            OpcodeType::OpReturn => Self::OpReturn,
            OpcodeType::OpForLoop => Self::OpForLoop,
            OpcodeType::OpForPrep => Self::OpForPrep,
            OpcodeType::OpTForLoop => Self::OpTForLoop,
            OpcodeType::OpSetList => Self::OpSetList,
            OpcodeType::OpClose => Self::OpClose,
            OpcodeType::OpClosure => Self::OpClosure,
            OpcodeType::OpVarArg => Self::OpVarArg,
        }
    }
}
