#[derive(Clone, Copy, Debug, PartialEq)]
pub enum VMOpcodeType {
    OpMove,
    OpLoadConst,
    OpLoadBool,
    OpLoadNil,
    OpGetUpval,
    OpGetGlobal,
    OpGetTable { constant_c: bool },
    OpSetGlobal,
    OpSetUpval,
    OpSetTable { constant_b: bool, constant_c: bool },
    OpNewTable,
    OpSelf { constant_c: bool },
    OpAdd { constant_b: bool, constant_c: bool },
    OpSub { constant_b: bool, constant_c: bool },
    OpMul { constant_b: bool, constant_c: bool },
    OpDiv { constant_b: bool, constant_c: bool },
    OpMod { constant_b: bool, constant_c: bool },
    OpPow { constant_b: bool, constant_c: bool },
    OpUnm,
    OpNot,
    OpLen,
    OpConcat,
    OpJmp,
    OpEq { constant_b: bool, constant_c: bool },
    OpLt { constant_b: bool, constant_c: bool },
    OpLe { constant_b: bool, constant_c: bool },
    OpTest,
    OpTestSet,
    OpCall,
    OpTailCall,
    OpReturn,
    OpForLoop,
    OpForPrep,
    OpTForLoop,
    OpSetList,
    OpClose,
    OpClosure,
    OpVarArg,
}
